### ISSUE TITLE
pretrain

### ISSUE THREAD

**Issue by kongjian408** [EricXY0706/ACVPred#1]
你好，请问那个预训练的文件能发给我吗

**Comment by EricXY0706** [comment]
Datasets used in pre-training are already in the repository.

**Comment by EricXY0706** [comment]
> 你好，请问那个预训练的文件能发给我吗
Datasets used in pre-training are already in the repository.

**Comment by kongjian408** [comment]
不好意思，你可能理解错我的意思，我指的是你的预训练和微调的完整代码，我不知道你的参数是多少，实在抱歉
